version: "3.0"

networks:
  needys-api-need:

services:
  needys-api-need:
    container_name: needys-api-need
    image: needys-api-need:latest
    ports:
      - 8010:8010
      - 8090:8090
    volumes:
      - ./../:/application
    networks:
      - needys-api-need
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/live"]
      interval: 5s
      timeout: 3s
      retries: 20

  mariadb:
    image: mariadb:10.5.1
    hostname: db.needys.local
    environment:
      MYSQL_DATABASE: needys
      MYSQL_ROOT_PASSWORD: needysroot
      MYSQL_USER: needys
      MYSQL_PASSWORD: needys
    ports:
      - 3306:3306
    networks:
      - needys-api-need

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-needys}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-rabbitmq}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - needys-api-need
